I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 116, in script
    i "[whisters] These guys are worth the time of the day. Pay em no mind and just walk by."
KeyError: u'whisters'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 116, in script
    i "[whisters] These guys are worth the time of the day. Pay em no mind and just walk by."
  File "/Users/Fusion/Dropbox/06 video games/renpy(mac)-7.4.11-sdk/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Users/Fusion/Dropbox/06 video games/renpy(mac)-7.4.11-sdk/renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "/Users/Fusion/Dropbox/06 video games/renpy(mac)-7.4.11-sdk/renpy/character.py", line 1236, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "/Users/Fusion/Dropbox/06 video games/renpy(mac)-7.4.11-sdk/renpy/character.py", line 1155, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "/Users/Fusion/Dropbox/06 video games/renpy(mac)-7.4.11-sdk/renpy/character.py", line 1135, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/Users/Fusion/Dropbox/06 video games/renpy(mac)-7.4.11-sdk/renpy/substitutions.py", line 270, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'whisters'

Darwin-21.0.1-x86_64-i386-64bit
Ren'Py 7.4.11.2266
Death Is Not the End - test 1.0
Sun May  8 11:27:48 2022
